[package]
name = "leaf"
version = "0.1.0"
authors = ["Vail Dorchester <vail.dorchester@colorado.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = {version = "*", features = ["specs-derive"] }
vulkano = "0.28"
vulkano-shaders = "0.28"
vulkano-win = "0.28"
egui = "*"
egui-winit = "*"
egui_vulkano = "*"
winit = "0.26.1"
simple_logger = "*"
log = {version = "*"}#, features = ["max_level_error", "release_max_level_error"]}
# euler = "*"
cgmath = "*"
